# shell tools
cask "iterm2"
brew "tmux"
brew "zsh"
brew "zsh-syntax-highlighting"

# vim
brew "nvim"
brew "ctags"

# search tools
brew "the_silver_searcher"

# keyboard tools
cask "karabiner-elements"


# languages
brew "node"
brew "go"
