unbind-key C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

bind-key \\ split-window -h
bind-key - split-window -v

bind-key -n C-h if -F "#{m/r:^(n?vim|view|l?nvim?)(diff)?$,#{pane_current_command}}" "send-keys C-h" "select-pane -L"
bind-key -n C-j if -F "#{m/r:^(n?vim|view|l?nvim?)(diff)?$,#{pane_current_command}}" "send-keys C-j" "select-pane -D"
bind-key -n C-k if -F "#{m/r:^(n?vim|view|l?nvim?)(diff)?$,#{pane_current_command}}" "send-keys C-k" "select-pane -U"
bind-key -n C-l if -F "#{m/r:^(n?vim|view|l?nvim?)(diff)?$,#{pane_current_command}}" "send-keys C-l" "select-pane -R"

set-window-option -g mode-keys vi
set-option -g status-keys vi

set-option -g mouse on
